### ISSUE TITLE
Triple action tanks are invisible

### ISSUE THREAD

**Issue by quicksilver7837** [libretro/FreeIntv#12] opened 2018-03-04 20:35 UTC
Running triple action tanks on my rpi 3. Tanks are invisible and shooting instantly destroys your own tank.

**Comment by gingerbeardman** [comment] 2018-04-11 15:24
The shooting issue is separate and most likely a dupe of: https://github.com/libretro/FreeIntv/issues/18

**Comment by Keltron3030** [comment] 2018-12-23 05:54
Oh, by the way, this latest version breaks a lot of other things that used to work... Astrosmash now destroys two asteroids at once if they're in the same y-axis, stampede cowboy now affects cows as if he spanned the whole y-axis, space Armada is now unplayable...instant death on start.  These are just the few I tested.

**Comment by gingerbeardman** [comment] 2018-12-23 09:37
@Keltron3030 thanks for the report! cc @recompileorg

**Comment by recompileorg** [comment] 2019-02-05 06:21
@Keltron3030

Sorry for the delay.  You're right.  I need to redo the whole STIC implementation.  It shouldn't take more than a couple days, I just need a little free time to do it.

**Comment by Keltron3030** [comment] 2019-02-05 11:01
Cool, thanks for the response.

**Comment by quicksilver7837** [comment] 2019-03-05 19:33
Should this be closed now? Wasnt sure if fix was fully implemented yet.

**Comment by recompileorg** [comment] 2019-03-05 19:35
Not yet.  I haven't got around to it.

**Closed** 2019-10-23 06:15 UTC

**Comment by quicksilver7837** [comment] 2019-10-28 13:40
Tanks are no longer invisible but the issue with your own shot destroying you still remains somewhat. Occasionally if you rapid fire your shots one of them will instantly blow you up. Would it be best to open as a new/separate issue?
